### PR TITLE
MassInstallAction: Install the CI workflow on this repository

### PR DESCRIPTION
**Pull request by timholy**
This pull request sets up the CI workflow on this repository.

### CODE REVIEW

**Comment by ViralBShah** [comment]
The tests run fine locally for me, but not in CI. @daviehh Since you provided the PR that made this package run on my mac, I wonder if you have any thoughts here.

**Comment by ViralBShah** [comment]
Merging this to switch on the CI, and subsequent PRs need to make the CI pass.

**Comment by ViralBShah** [comment]
@giordano @staticfloat Would you know why these tests that are basically dlopening Accelerate and calling simple functions, failing in CI, but would pass locally?

**Comment by daviehh** [comment]
According to the report in https://github.com/JuliaMath/AppleAccelerate.jl/pull/43#issuecomment-1101479528, it may be a macos bug: some version in of macos 11.x may have some bugs that missed some symbols; all test runs fine on 12.x

**Pull request merged**
